---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "1 - Workshop Tips"
      solveButton: false
    - name: module-02
      label: "2 - Exploring the web-UI and Dashboard"
      solveButton: false
    - name: module-03
      label: "3 - Creating an Inventory"
      solveButton: true
    - name: module-04
      label: "4 - Creating your first Project"
      solveButton: true
    - name: module-05
      label: "5 - Get to know Credentials"
      solveButton: true
    - name: module-06
      label: "6 - Creating a Job Template"
      solveButton: true
    - name: module-07
      label: "7 - Creating a second Project"
      solveButton: true
    - name: module-08
      label: "8 - Creating a second and third Job Template"
      solveButton: true
    - name: module-09
      label: "9 - Creating a Workflow Job Template"
      solveButton: true
    - name: module-10
      label: "10 - Creating a Job Template with a Survey"
      solveButton: true


tabs:
  - name: Automation Controller
    url: https://control-${guid}.${domain}/
  - name: ">_ Terminal"
    url: /wetty
  - name: "Node1 Web"
    url: https://node1-${guid}.${domain}/index.html
    modules:
     - module-06
  - name: "Node2 Web"
    url: https://node2-${guid}.${domain}/index.html
    modules:
     - module-06


  # - name: Windows RDP
  #   url: https://windows-ironrdp-${guid}.${domain}/
  #   external: false
  # - name: ">_ control"
  #   url: /wetty
  # - name: ">_ node01"
  #   url: /wetty_node01
  # - name: ">_ node02"
  #   url: /wetty_node02
  # - name: ">_ node03"
  #   url: /wetty_node03
  # - name: Cloud (PoC)
  #   url: /cloud
