---
# Containers are under development
containers:
  - name: gitea
    image: quay.io/acme_corp/gitea-rootless
    ports:
      - name: gitea
        containerPort: 3000
        protocol: TCP
    environment:
      GITEA__DEFAULT__RUN_MODE: dev
      GITEA__database__DB_TYPE: sqlite3
      GITEA__database__PATH: /data/gitea/gitea.db
      GITEA__picture__DISABLE_GRAVATAR: "true"
      GITEA__repository__DEFAULT_PRIVATE: "false"
      GITEA__repository__DEFAULT_PUSH_CREATE_PRIVATE: "false"
      GITEA__repository__ENABLE_PUSH_CREATE_ORG: "true"
      GITEA__repository__ENABLE_PUSH_CREATE_USER: "true"
      GITEA__repository__ONLY_ALLOW_PUSH_IF_GITEA_ENVIRONMENT_SET: "false"
      GITEA__security__INSTALL_LOCK: "true"
      GITEA__server__SSH_DOMAIN: http://gitea
      GITEA__service__DISABLE_REGISTRATION: "true"
      GITEA__service__REQUIRE_SIGNIN_VIEW: "false"
      GITEA__webhook__ALLOWED_HOST_LIST: '*'
    volumeMounts:
      - name: gitea-varlib
        mountPath: /var/lib/gitea/
      - name: gitea-data
        mountPath: /data/
      - name: gitea-etc
        mountPath: /etc/gitea
    volumes:
      - name: gitea-data
        emptyDir: {}
      - name: gitea-etc
        emptyDir: {}
      - name: gitea-varlib
        emptyDir: {}
    commands: 
        - gitea admin user create --admin --username gitea --password gitea --email dummy@dummy.com --must-change-password=false
        - >
          curl -X POST -H "accept: application/json" -H "Content-Type: application/json"
          -u 'gitea:gitea' 
          -d '{"username": "student", "full_name": "student", "description": "student"}'
          http://localhost:3000/api/v1/orgs
        - >
          curl -X POST -H "accept: application/json" -H "Content-Type: application/json"
          -u 'gitea:gitea'
          -d '{"clone_addr": "https://github.com/ansible-tmm/controller-101.git", "repo_name": "controller-101", "owner": "student", "uid": 2, "private": false}'
          http://localhost:3000/api/v1/repos/migrate
    memory: 2Gi
    services:
      - name: gitea
        ports:
          - port: 3000
            protocol: TCP
            targetPort: 3000
            name: gitea
    routes:
      - name: gitea
        host: gitea
        service: gitea
        targetPort: 3000
        tls: true
        tls_termination: Edge
virtualmachines:
  - name: "control"
    image: "aap-2.7-2-cehm-20260630"
    memory: "32G"
    cores: 4
    image_size: "70Gi"
   # disk_type: "scsi"
   # bootloader: "efi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd
    services:
      - name: control-https
        ports:
          - port: 443
            protocol: TCP
            targetPort: 8443
            name: control-https
    routes:
      - name: control-https
        host: control
        service: control-https
        targetPort: 443
        tls: true
        tls_termination: reencrypt
        tls_destinationCACertificate: |
          -----BEGIN CERTIFICATE-----
          MIIF1jCCA76gAwIBAgIUVGPtWdIAzaYcfh4q6N+SFxa9OS0wDQYJKoZIhvcNAQEL
          BQAwgYIxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4G
          A1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHUmVkIEhhdDEQMA4GA1UECwwHQW5zaWJs
          ZTEkMCIGA1UEAwwbQW5zaWJsZSBBdXRvbWF0aW9uIFBsYXRmb3JtMB4XDTI2MDYz
          MDIwNDE0OVoXDTM2MDYyNzIwNDE0OVowgYIxCzAJBgNVBAYTAlVTMRcwFQYDVQQI
          DA5Ob3J0aCBDYXJvbGluYTEQMA4GA1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHUmVk
          IEhhdDEQMA4GA1UECwwHQW5zaWJsZTEkMCIGA1UEAwwbQW5zaWJsZSBBdXRvbWF0
          aW9uIFBsYXRmb3JtMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvezK
          CQJvMlpju7a+BdEDwLOzW1/svKWnU3jiW58R36ftglZq2FtLSfT11CJ+khjVQsfa
          WCgQIU0QvKurWLWbq5ACcsptZ8RTSy/oQWlKJqjF8t6PlJcGdCLy9d+zsaJP6K05
          IwKABLCBisepXf4GNJzSe+tGXq2tT+8hldS6Xo/zeNsDN7QX+n/JnbyOoGAC4rlp
          5vTTQMPDaMZYLrhTEzLNoY8PSaZIOZUCJnrBgTFJYWp8PN92XuE9AuCK5CIoiZga
          yrTKl5z3YhLo6hx52qzhWhjbBm9gll3tVfxIzpEoBzfAmHDSu8LXNYhMwprOD41P
          EmjyE9QfdBdTHO67MSEe8VgD6P7AQla9xXuy7ChjcQfLEponfWzdqA7qksneIUEa
          QGBhuUagRssH3fWhgW91VdpJesRvhJLHR/UI85p99j3EkUYlhFdYHFGSjImSLhHr
          2DReta/Q4Sj66rTSJjjQCLcxvCaTPzRFPLHR2adn6j3UF1C6eUxshE6fQdtGCOma
          ARigrRake5p5WxOvxNFGgXEEOrxzeY4m1Y+2kHojwVNFUqhJPUJNGoXq3c7uqcvd
          wksTq+F0qrYczQ0yq4ErwPq5etjdG7DoQJ/VHL0sxtSB4cD9dXYsB3ZANm6P9LHK
          Q/quMmaBrUri8BRwC4h/a5QVNrx1DoXRF/uLfvkCAwEAAaNCMEAwDgYDVR0PAQH/
          BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFNOIAvAqnlTbd8at9ZlU
          JyRzo5XRMA0GCSqGSIb3DQEBCwUAA4ICAQC6workqBiG9GJ5brH8YJtgIuQaOI0b
          vkppSjzox01zyRSxgZWdudZjVsGM+ZaHdCuUlBKT4K5dSW7X+PCFKmMmXAFERb1+
          ZCf5Gz4WoMi1Gy7LMLCU7zH0T6uSR7+400TIcilhdc50MrwkahdW2/01Qxww5mPv
          /0onYYwGMQdXyIkVsHk6TN546nCnopEKZeR6EUCV8Zn/Rnq8gKgu/fYUy5XoVHe7
          T5oTukKZAwXtPj1CUeqd8T3uC26sc3xajI8Qw92zX5uDpSqEfRtFr+u6YdRoN3b/
          H4R/MmP1Ko9Y+LBTihK1T6afs35d0XndfEvUWJDdOfoHmHzq7CL0QTRe76pe5F8R
          9oaP17RCpqzf5aBVgftng8QgJc4ODKKmWeVDJ7T/4INIxnjQm0bXhD9QkFi9uEtJ
          /yyGJjkH3CjDt4w3okYPzLCbA9zpoA1zwr4QWDFEadQrwEB36Sx4LEu0+GMicpad
          J3f2y70NfgQMv8aJAOxH8QvkLU+ORCaUcZiw1NPLu+YMBOECtBtoD4wph2W5UTB1
          s9OFcAQSBiDzyZsCLGXp1goc2JZDPHbU2iFtqBvdwNRH3z2T8v7u7SFmkbrqkxHH
          +1wp72F2cdzig52epPASbAKsZhHU+d3feKGtglf/hkNmE99ma4fTAh8HZ8hu5Rxk
          5vSdMHKkmMRv0w==
          -----END CERTIFICATE-----

  - name: "node1"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: node1-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: node01
    routes:
      - name: node1-web
        host: node1
        service: node1-http
        targetPort: 80
        tls: true  ## To resolve https/http Framing
        tls_termination: Edge ## To resolve https/http Framing 
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }  
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd

        
  - name: "node2"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: node2-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: node2
    routes:
      - name: node2-web
        host: node2
        service: node2-http
        targetPort: 80
        tls: true  ## To resolve https/http Framing
        tls_termination: Edge ## To resolve https/http Framing
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }  
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd
        
  - name: "node3"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }  
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd
