---
# Containers are under development
containers:
  - name: gitea
    image: quay.io/acme_corp/gitea-rootless
    ports:
      - name: gitea
        containerPort: 3000
        protocol: TCP
    environment:
      GITEA__DEFAULT__RUN_MODE: dev
      GITEA__database__DB_TYPE: sqlite3
      GITEA__database__PATH: /data/gitea/gitea.db
      GITEA__picture__DISABLE_GRAVATAR: "true"
      GITEA__repository__DEFAULT_PRIVATE: "false"
      GITEA__repository__DEFAULT_PUSH_CREATE_PRIVATE: "false"
      GITEA__repository__ENABLE_PUSH_CREATE_ORG: "true"
      GITEA__repository__ENABLE_PUSH_CREATE_USER: "true"
      GITEA__repository__ONLY_ALLOW_PUSH_IF_GITEA_ENVIRONMENT_SET: "false"
      GITEA__security__INSTALL_LOCK: "true"
      GITEA__server__SSH_DOMAIN: http://gitea
      GITEA__service__DISABLE_REGISTRATION: "true"
      GITEA__service__REQUIRE_SIGNIN_VIEW: "false"
      GITEA__webhook__ALLOWED_HOST_LIST: '*'
    volumeMounts:
      - name: gitea-varlib
        mountPath: /var/lib/gitea/
      - name: gitea-data
        mountPath: /data/
      - name: gitea-etc
        mountPath: /etc/gitea
    volumes:
      - name: gitea-data
        emptyDir: {}
      - name: gitea-etc
        emptyDir: {}
      - name: gitea-varlib
        emptyDir: {}
    commands: 
        - gitea admin user create --admin --username gitea --password gitea --email dummy@dummy.com --must-change-password=false
        - >
          curl -X POST -H "accept: application/json" -H "Content-Type: application/json"
          -u 'gitea:gitea' 
          -d '{"username": "student", "full_name": "student", "description": "student"}'
          http://localhost:3000/api/v1/orgs
        - >
          curl -X POST -H "accept: application/json" -H "Content-Type: application/json"
          -u 'gitea:gitea'
          -d '{"clone_addr": "https://github.com/ansible-tmm/controller-101.git", "repo_name": "controller-101", "owner": "student", "uid": 2, "private": false}'
          http://localhost:3000/api/v1/repos/migrate
    memory: 2Gi
    services:
      - name: gitea
        ports:
          - port: 3000
            protocol: TCP
            targetPort: 3000
            name: gitea
    routes:
      - name: gitea
        host: gitea
        service: gitea
        targetPort: 3000
        tls: true
        tls_termination: Edge
virtualmachines:
  - name: "control"
    image: "aap-27-base-ceh"
    memory: "32G"
    cores: 4
    image_size: "70Gi"
   # disk_type: "scsi"
   # bootloader: "efi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd
    services:
      - name: control-https
        ports:
          - port: 443
            protocol: TCP
            targetPort: 443
            name: control-https
    routes:
      - name: control-https
        host: control
        service: control-https
        targetPort: 443
        tls: true
        tls_termination: reencrypt
        tls_destinationCACertificate: |
          -----BEGIN CERTIFICATE-----
          MIIF1jCCA76gAwIBAgIUObLKmj1zeqIzzHjffruq/7mGSQswDQYJKoZIhvcNAQEL
          BQAwgYIxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4G
          A1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHUmVkIEhhdDEQMA4GA1UECwwHQW5zaWJs
          ZTEkMCIGA1UEAwwbQW5zaWJsZSBBdXRvbWF0aW9uIFBsYXRmb3JtMB4XDTI2MDYw
          NzE1MzkyNVoXDTM2MDYwNDE1MzkyNVowgYIxCzAJBgNVBAYTAlVTMRcwFQYDVQQI
          DA5Ob3J0aCBDYXJvbGluYTEQMA4GA1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHUmVk
          IEhhdDEQMA4GA1UECwwHQW5zaWJsZTEkMCIGA1UEAwwbQW5zaWJsZSBBdXRvbWF0
          aW9uIFBsYXRmb3JtMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAqvym
          4YlTW1AHbgc+JaKr2hEF3OUzqlCu+8shKmE+nmEG677/dCSMpvrd6e77UY6ssphn
          PVFLTutmqe6brFD6SSuhoPYTEA/VVgBQNCKYE6ODo5gqy4uSJEZ3AGVIdfJM2lNq
          XibjMlABaZbHWIob6rGl5YG4zBlkLn1ZgiyKeUiScHGeeSBTAzpFNRa79c/5TIWf
          WgDmkbmKvQQXorUK49EW5drSCGc2PjIN/2XZ5ovp2cGqaIQSN8KYifDtYSSehl8d
          IoXXemkSZMK2ZAF46Rf9n2kLAyynr42coKeJgyJ8F3eCmFMdQFq67TEYT8RM7UvL
          hH+0b8aO9IGJZM91pUmt4GU7UDyOWDPdVXnlsf+VRtf5442o1RqoZhOsJkLXzOR6
          hbrGd3PHXcIu0lY4RAX/ET4sTtlmp3Uuiv460MZcfkWh5Nuyn1lcnJid7535B2R1
          Xy/5XRsXWi9846G8WYAPN0JZa1ekdwKAQETackSYeHLBNsOgVEObBQmfWqyucrzW
          q0nv51fAS1Im3uKbgPqwiIsnjAfAExuo+rMy2A7c1lpYNTmbcsoAVbQ7t9E1fX4A
          LJU1AmU3NsTJoXARHt7GCHitu7QOOxqlcUWmTFnS16bhcGE2GDdjE6UQR/X56O7L
          YMykbvWygh3uq8wpU+009gS8keleLcJp2ZRPxd8CAwEAAaNCMEAwDgYDVR0PAQH/
          BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFC77M+VIXnxhEgPr0rkl
          nxXzBsdWMA0GCSqGSIb3DQEBCwUAA4ICAQAGrSuKQwIu8Z++vPyc0oPLSvZxU0+E
          LUGPzgOkJvDxZ2oXC8m14ksVfccCrEYhaRaGU/lLxU3M/9e1R7nDVGK7smgvJjOP
          cbdt8pQgGwuI0JFBZSJT8pkm9XeIygrDbTmAX+YQWVo5tqHCZrxL7WR4IDU11SVf
          i/rSJlt81vX9OXNXbC5pRGtthD/jsx/l+TVWTBvZ/poK0N3bH+JM7D6bdakvQZCf
          iBbdl1tFMdU8hTcz01lFzOUp0AYKjpG8NAmhKgmegc+JW+yKsbnEPqE1t++5L9Sk
          x6RkSmVr5wZ32OcctoHuxxZuw+7zE8M3uWLiLNlMza7CJ4oSuQIk5qqEaI42x+zT
          suKYoqM7LJ2w8o9c9YQwtyvcO5BaMOB4NTdLjc2gPHIQCFsGRLJgwbY/wh5iCzih
          yTBT6TtL4JPSJ7A+4mX50iY9lS2PXp91Hmu3D24DLWDKZWh0CLxQWt8hLkdZerJC
          ERwSzq+mTJqXc2kp+iUq9qZFgU6hnIKtIqSbG+C4B5JNezUQrRPlV2+1VS76o11w
          6s43F8wW2/aiuflj8/Xi4KLj21g/x3BRkvUlhr+EquzUEi1SJOZjlwELR4jCNAAl
          CdcUKqmAqDrwFFfXFclbD/b5CPUV0EVBfxhRp+wKMduX7vvrK5DOB4OUWjpZi5zJ
          IPLsgeSwT8qCxw==
          -----END CERTIFICATE-----

  - name: "node1"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: node1-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: node01
    routes:
      - name: node1-web
        host: node1
        service: node1-http
        targetPort: 80
        tls: true  ## To resolve https/http Framing
        tls_termination: Edge ## To resolve https/http Framing 
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }  
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd

        
  - name: "node2"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: node2-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: node2
    routes:
      - name: node2-web
        host: node2
        service: node2-http
        targetPort: 80
        tls: true  ## To resolve https/http Framing
        tls_termination: Edge ## To resolve https/http Framing
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }  
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd
        
  - name: "node3"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }  
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd
