---
# Containers are under development
containers:
  - name: gitea
    image: quay.io/acme_corp/gitea-rootless
    ports:
      - name: gitea
        containerPort: 3000
        protocol: TCP
    environment:
      GITEA__DEFAULT__RUN_MODE: dev
      GITEA__database__DB_TYPE: sqlite3
      GITEA__database__PATH: /data/gitea/gitea.db
      GITEA__picture__DISABLE_GRAVATAR: "true"
      GITEA__repository__DEFAULT_PRIVATE: "false"
      GITEA__repository__DEFAULT_PUSH_CREATE_PRIVATE: "false"
      GITEA__repository__ENABLE_PUSH_CREATE_ORG: "true"
      GITEA__repository__ENABLE_PUSH_CREATE_USER: "true"
      GITEA__repository__ONLY_ALLOW_PUSH_IF_GITEA_ENVIRONMENT_SET: "false"
      GITEA__security__INSTALL_LOCK: "true"
      GITEA__server__SSH_DOMAIN: http://gitea
      GITEA__service__DISABLE_REGISTRATION: "true"
      GITEA__service__REQUIRE_SIGNIN_VIEW: "false"
      GITEA__webhook__ALLOWED_HOST_LIST: '*'
    volumeMounts:
      - name: gitea-varlib
        mountPath: /var/lib/gitea/
      - name: gitea-data
        mountPath: /data/
      - name: gitea-etc
        mountPath: /etc/gitea
    volumes:
      - name: gitea-data
        emptyDir: {}
      - name: gitea-etc
        emptyDir: {}
      - name: gitea-varlib
        emptyDir: {}
    commands: 
        - gitea admin user create --admin --username gitea --password gitea --email dummy@dummy.com --must-change-password=false
        - >
          curl -X POST -H "accept: application/json" -H "Content-Type: application/json"
          -u 'gitea:gitea' 
          -d '{"username": "student", "full_name": "student", "description": "student"}'
          http://localhost:3000/api/v1/orgs
        - >
          curl -X POST -H "accept: application/json" -H "Content-Type: application/json"
          -u 'gitea:gitea'
          -d '{"clone_addr": "https://github.com/ansible-tmm/controller-101.git", "repo_name": "controller-101", "owner": "student", "uid": 2, "private": false}'
          http://localhost:3000/api/v1/repos/migrate
    memory: 2Gi
    services:
      - name: gitea
        ports:
          - port: 3000
            protocol: TCP
            targetPort: 3000
            name: gitea
    routes:
      - name: gitea
        host: gitea
        service: gitea
        targetPort: 3000
        tls: true
        tls_termination: Edge
virtualmachines:
  - name: "control"
    image: "aap-2.7-2-cehm-20260630"
    memory: "32G"
    cores: 4
    image_size: "70Gi"
   # disk_type: "scsi"
   # bootloader: "efi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd
    services:
      - name: control-https
        ports:
          - port: 443
            protocol: TCP
            targetPort: 443
            name: control-https
    routes:
      - name: control-https
        host: control
        service: control-https
        targetPort: 443
        tls: true
        tls_termination: reencrypt
        tls_destinationCACertificate: |
          -----BEGIN CERTIFICATE-----
          MIIF/TCCA+WgAwIBAgIUL7V0y///BJFRx5c3SvDKkvHlqOUwDQYJKoZIhvcNAQEL
          BQAwgYIxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4G
          A1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHUmVkIEhhdDEQMA4GA1UECwwHQW5zaWJs
          ZTEkMCIGA1UEAwwbQW5zaWJsZSBBdXRvbWF0aW9uIFBsYXRmb3JtMB4XDTI2MDYz
          MDIwNDU1MFoXDTM2MDYyNzIwNDU1MFowdjELMAkGA1UEBhMCVVMxFzAVBgNVBAgM
          Dk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRAwDgYDVQQKDAdSZWQg
          SGF0MRAwDgYDVQQLDAdBbnNpYmxlMRgwFgYDVQQDDA9hYXAuZXhhbXBsZS5vcmcw
          ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC3lz7eJcyjdz8v0QCzoqJd
          X43LMywQ7JFsZ2z+e/LSOC9r15IP/QWX1Pdi+VLdIMPzsq+AqFXss88t1O4RJZ6B
          /DjLfmsTLf1vAtgQWxeObQSz+hgFeD7BeOaUlljePazxmD1U1aNYipRzVKMdfWxV
          pZgX/5MPuFWObYhjowSHuGnbQksfJk00+6c9TL2afqMGj9yE5XTZJ/lnf/1gu2W/
          1WQGhWJMVlWlejEQfrfPyTKrc+WIOVRUWvNTjVhCo0SJASm70siq/YUYk2EO2Kt/
          d72MOPMX137WAUKDt0PA2rRcv+BfuLxgKGKsgz3ppvWHAc/Z8BnOorWqGj/JZDmA
          5VyxtlR4lflHxt1GWWmHAC1q3y2IZggvDt4/Bjf8lu9hDUZAJdUp3fUGxar+iFYS
          JGQWqVIt/GIve8e9or+hcO1YEgOTatDPqQG/Ofevs8E4QwxKFslHIBqAZkMtOAPn
          IsDt6Yz5R5W5KLXUmXu8DVnFdwUBx4W+h5u/G3cJgP4+hDnEgH64AHCsEPsSSB1Z
          YMH9h5Gr9sqOWmwWbjTIYQypnogQ1XsGp9cMgeBJpxZ28W6h+Q/y80lUq1/PF70M
          nlnWpKWlTpepvF//qZLsgkz0LWkDP2nXyuoufFT4ZfOxxFYKSO6Yi+9Z4Sq+XkZJ
          4P0iMnQYGgdhSFSRRRKmHQIDAQABo3YwdDAyBgNVHREEKzApgg9hYXAuZXhhbXBs
          ZS5vcmeHBKwfLWuHEP6AAAAAAAAADBQA//400WEwHQYDVR0OBBYEFFAiChz7tkuI
          XVz6AihqGoaBBWVlMB8GA1UdIwQYMBaAFNOIAvAqnlTbd8at9ZlUJyRzo5XRMA0G
          CSqGSIb3DQEBCwUAA4ICAQAANNT8Q5M8ikPQEBqwtAXExuQsdKBstPUiSfB/5+ck
          JKbpB28I5k5Weh7Jdf888ycMnBNWCzGK2DpmE4xCRPZL5/OyT9jFID2tZHljH56g
          QYtKuu/TS5XV2ug4MCvUbcmyiIyK+ikGFJrl7mMXscV0S9gchjLj6LhTzmE1GXx9
          q3Sam0yJ0073rt49pSev91nZn5eoI0ySQUFvFuCxXHs1cG3S94BeZgVr5efMmKkI
          8URoEGelumL0UJCE/hO7CEBBl+RC854pUABJPdoEc4wBVNVhU1Midl1wbnrtHaBA
          zNFCMUWCrBIy0ErabW76PhiQonRD8nwONeDVFCUznqC2icRs5l3HWCU4cK71iusp
          uKCsUNvKKv6zj2gUWid5kBJ2fy6mv02wHWBmLxOl0KlIuGlNWn4WCZbuWb7Ige7V
          ZU23mEP6uRgxclsMAz/iPekaZ3jt6p4U3M7yjYtdZ09FbbTiK5UEw//Gmm1t6O1v
          4O3mxph/97jHbDuCiLNAMJ+xEtM1Kb1syaIplMWzcRAINWwgzn5p5BUB1wN0AXlL
          3XYwL58kAdSnzhf+Dfqz54UXPliXK2RcAVz4EQaHB0rCaGG5T3Xd/fFPMbxYyrAb
          KVgYFYwzDGbDCFqV7oXqLcAvAFNPj6/pvZMIuY/fF14IBk9XiiV5ZtRwOGudoT8i
          Lg==
          -----END CERTIFICATE-----

  - name: "node1"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: node1-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: node01
    routes:
      - name: node1-web
        host: node1
        service: node1-http
        targetPort: 80
        tls: true  ## To resolve https/http Framing
        tls_termination: Edge ## To resolve https/http Framing 
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }  
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd

        
  - name: "node2"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: node2-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: node2
    routes:
      - name: node2-web
        host: node2
        service: node2-http
        targetPort: 80
        tls: true  ## To resolve https/http Framing
        tls_termination: Edge ## To resolve https/http Framing
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }  
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd
        
  - name: "node3"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }  
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd
